services:
  kaitopia_db:
    image: postgres:17
    hostname: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 256M

  firebase_emulator:
    build:
      context: ./docker/firebase
      dockerfile: Dockerfile
    volumes:
      - ./docker/firebase:/usr/src/app
    ports:
      - "4000:4000" # Emulator UI
      - "9099:9099" # Firebase Auth
      - "8080:8080" # Firebase Firestore
    environment:
      NODE_ENV: development
    command:
      [
        "firebase",
        "emulators:start",
        "--only",
        "auth,firestore",
        "--import=./init-data",
      ]

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #     PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - kaitopia_db
  #   volumes:
  #     - ./pgadmin.config.json:/pgadmin4/servers.json

volumes:
  postgres_data:
    driver: local
