import {
  Exercise,
  Question,
  QuestionAnswer,
  QuestionVersion,
} from "@prisma/client"

export const SeedDataIntroProgramming1 = {
  exercise: {
    id: "intro_programming_1",
    title: "プログラミング入門",
    schoolId: "kaitopia_1",
    description: "プログラミングの基礎を学ぶための問題集です。",
    isPublished: true,
  } as Exercise,

  questions: [
    {
      id: "intro_programming_1_1",
      title: "プログラミング入門 問題1",
      questionType: "TEXT",
      answerType: "SELECT",
      schoolId: "kaitopia_1",
      currentVersionId: null,
    },
    {
      id: "intro_programming_1_2",
      title: "プログラミング入門 問題2",
      questionType: "TEXT",
      answerType: "SELECT",
      schoolId: "kaitopia_1",
      currentVersionId: null,
    },
    {
      id: "intro_programming_1_3",
      title: "プログラミング入門 問題3",
      questionType: "TEXT",
      answerType: "SELECT",
      schoolId: "kaitopia_1",
      currentVersionId: null,
    },
    {
      id: "intro_programming_1_4",
      title: "プログラミング入門 問題4",
      questionType: "TEXT",
      answerType: "SELECT",
      schoolId: "kaitopia_1",
      currentVersionId: null,
    },
    {
      id: "intro_programming_1_5",
      title: "プログラミング入門 問題5",
      questionType: "TEXT",
      answerType: "SELECT",
      schoolId: "kaitopia_1",
      currentVersionId: null,
    },
    {
      id: "intro_programming_1_6",
      title: "プログラミング入門 問題6",
      questionType: "TEXT",
      answerType: "SELECT",
      schoolId: "kaitopia_1",
      currentVersionId: null,
    },
    {
      id: "intro_programming_1_7",
      title: "プログラミング入門 問題7",
      questionType: "TEXT",
      answerType: "SELECT",
      schoolId: "kaitopia_1",
      currentVersionId: null,
    },
    {
      id: "intro_programming_1_8",
      title: "プログラミング入門 問題8",
      questionType: "TEXT",
      answerType: "SELECT",
      schoolId: "kaitopia_1",
      currentVersionId: null,
    },
    {
      id: "intro_programming_1_9",
      title: "プログラミング入門 問題9",
      questionType: "TEXT",
      answerType: "SELECT",
      schoolId: "kaitopia_1",
      currentVersionId: null,
    },
    {
      id: "intro_programming_1_10",
      title: "プログラミング入門 問題10",
      questionType: "TEXT",
      answerType: "SELECT",
      schoolId: "kaitopia_1",
      currentVersionId: null,
    },
  ] as Question[],

  questionVersions: [
    {
      questionId: "intro_programming_1_1",
      version: 1,
      content: "コンピュータにおいて「プログラム」とはどのようなものですか？",
      hint: "",
    },
    {
      questionId: "intro_programming_1_2",
      version: 1,
      content:
        "プログラミングで使用される基本的な制御構文として正しいものをすべて選びなさい。",
      hint: "",
    },
    {
      questionId: "intro_programming_1_3",
      version: 1,
      content: "フローチャートで「ひし形」で表されるのはどのような処理か？",
      hint: "",
    },
    {
      questionId: "intro_programming_1_4",
      version: 1,
      content: "次のうち「論理演算子」として使われるものをすべて選びなさい。",
      hint: "",
    },
    {
      questionId: "intro_programming_1_5",
      version: 1,
      content: "「変数」に関する説明として正しいものを選びなさい。",
      hint: "",
    },
    {
      questionId: "intro_programming_1_6",
      version: 1,
      content: "2進数の `1011` は、10進数でいくつか？",
      hint: "",
    },
    {
      questionId: "intro_programming_1_7",
      version: 1,
      content:
        "アルゴリズムにおける「探索（サーチ）」の方法として代表的なものをすべて選びなさい。",
      hint: "",
    },
    {
      questionId: "intro_programming_1_8",
      version: 1,
      content:
        "JavaScriptのようなインタプリタ言語に関する説明として正しいものはどれか？",
      hint: "",
    },
    {
      questionId: "intro_programming_1_9",
      version: 1,
      content:
        "次のうち、コンピュータの記憶装置に関する説明として正しいものをすべて選びなさい。",
      hint: "",
    },
    {
      questionId: "intro_programming_1_10",
      version: 1,
      content: "次のうち、プログラムのバグに対して行う適切な作業はどれか？",
      hint: "",
    },
  ] as QuestionVersion[],

  questionAnswers: [
    {
      questionId: "intro_programming_1_1",
      version: 1,
      answerId: "1",
      selectContent: "電源供給の方法",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_1",
      version: 1,
      answerId: "2",
      selectContent: "ハードウェアの構成要素",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_1",
      version: 1,
      answerId: "3",
      selectContent: "処理手順を記述した命令の集まり",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_1",
      version: 1,
      answerId: "4",
      selectContent: "インターネットの接続方式",
      isCorrect: false,
    },

    {
      questionId: "intro_programming_1_2",
      version: 1,
      answerId: "1",
      selectContent: "if文",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_2",
      version: 1,
      answerId: "2",
      selectContent: "repeat文",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_2",
      version: 1,
      answerId: "3",
      selectContent: "for文",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_2",
      version: 1,
      answerId: "4",
      selectContent: "connect文",
      isCorrect: false,
    },

    {
      questionId: "intro_programming_1_3",
      version: 1,
      answerId: "1",
      selectContent: "処理の開始",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_3",
      version: 1,
      answerId: "2",
      selectContent: "処理の終了",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_3",
      version: 1,
      answerId: "3",
      selectContent: "条件分岐",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_3",
      version: 1,
      answerId: "4",
      selectContent: "繰り返し処理",
      isCorrect: false,
    },

    {
      questionId: "intro_programming_1_4",
      version: 1,
      answerId: "1",
      selectContent: "AND",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_4",
      version: 1,
      answerId: "2",
      selectContent: "OR",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_4",
      version: 1,
      answerId: "3",
      selectContent: "NOT",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_4",
      version: 1,
      answerId: "4",
      selectContent: "NOR",
      isCorrect: true,
    },

    {
      questionId: "intro_programming_1_5",
      version: 1,
      answerId: "1",
      selectContent: "一度決めた値は変更できない",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_5",
      version: 1,
      answerId: "2",
      selectContent: "プログラム内で使われる文字列のこと",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_5",
      version: 1,
      answerId: "3",
      selectContent: "一時的に値を格納するための名前付き領域",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_5",
      version: 1,
      answerId: "4",
      selectContent: "ハードウェアを制御するための命令のこと",
      isCorrect: false,
    },

    {
      questionId: "intro_programming_1_6",
      version: 1,
      answerId: "1",
      selectContent: "9",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_6",
      version: 1,
      answerId: "2",
      selectContent: "11",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_6",
      version: 1,
      answerId: "3",
      selectContent: "13",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_6",
      version: 1,
      answerId: "4",
      selectContent: "15",
      isCorrect: false,
    },

    {
      questionId: "intro_programming_1_7",
      version: 1,
      answerId: "1",
      selectContent: "線形探索",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_7",
      version: 1,
      answerId: "2",
      selectContent: "2分探索",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_7",
      version: 1,
      answerId: "3",
      selectContent: "ハッシュ探索",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_7",
      version: 1,
      answerId: "4",
      selectContent: "全件更新",
      isCorrect: false,
    },

    {
      questionId: "intro_programming_1_8",
      version: 1,
      answerId: "1",
      selectContent: "コンパイル後に機械語に翻訳される",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_8",
      version: 1,
      answerId: "2",
      selectContent: "実行時に1行ずつ解釈しながら動作する",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_8",
      version: 1,
      answerId: "3",
      selectContent: "専用ハードウェアでのみ動作する",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_8",
      version: 1,
      answerId: "4",
      selectContent: "静的型付けが必須である",
      isCorrect: false,
    },

    {
      questionId: "intro_programming_1_9",
      version: 1,
      answerId: "1",
      selectContent: "RAMは揮発性メモリである",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_9",
      version: 1,
      answerId: "2",
      selectContent: "HDDは主記憶装置である",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_9",
      version: 1,
      answerId: "3",
      selectContent: "SSDはHDDより高速である",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_9",
      version: 1,
      answerId: "4",
      selectContent: "ROMは基本的に書き換えられない",
      isCorrect: true,
    },

    {
      questionId: "intro_programming_1_10",
      version: 1,
      answerId: "1",
      selectContent: "マージ",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_10",
      version: 1,
      answerId: "2",
      selectContent: "デバッグ",
      isCorrect: true,
    },
    {
      questionId: "intro_programming_1_10",
      version: 1,
      answerId: "3",
      selectContent: "コンパイル",
      isCorrect: false,
    },
    {
      questionId: "intro_programming_1_10",
      version: 1,
      answerId: "4",
      selectContent: "リファクタリング",
      isCorrect: false,
    },
  ] as QuestionAnswer[],
}
